// GENERATED by scripts/gen-armory.mjs — do not edit by hand.
//
// The Season 1 catalogue, derived from the mainnet mint record so it cannot disagree with
// what was actually minted, and cross-checked against common/entitlements.js so it cannot
// advertise an item that grants nothing.
//
// `slug` is both the mint-record key and the art filename: the token metadata points at
// https://sol-pkmn.fun/nft/degen-s1/<slug>.png, and this screen serves the same files, so
// the armour you see here is the image the marketplace shows.
//
// `mint` is ONE real asset of that type — enough to deep-link an item page. It is not a
// claim that this particular copy is listed.
//
// Collection: 5u2raT68foyJiMJPGHMZxkoZWs81djASsn4cfkQhQsUv
// Minted: 80 assets across 24 types

export const COLLECTION = '5u2raT68foyJiMJPGHMZxkoZWs81djASsn4cfkQhQsUv'

// Marketplace collection pages. Item-level links are built from a mint below.
export const TENSOR_COLLECTION = 'https://www.tensor.trade/trade/degentournament'
export const MAGIC_EDEN_COLLECTION = 'https://magiceden.io/marketplace/degen_tournament_season_1_armory'
export const tensorItem = (mint) => (mint ? `https://www.tensor.trade/item/${mint}` : TENSOR_COLLECTION)
export const magicEdenItem = (mint) => (mint ? `https://magiceden.io/item-details/${mint}` : MAGIC_EDEN_COLLECTION)

/** Art for an item, served from this origin (same files the token metadata points at). */
export const armoryArt = (slug) => `/nft/degen-s1/${slug}.png`

export const ARMORY_ITEMS = [
	{
		"slug": "smg",
		"name": "Static Repeater",
		"kind": "weapon",
		"label": "SMG",
		"finish": null,
		"weaponIndex": 1,
		"rarity": "Common",
		"supply": 10,
		"mint": "76hpqdjv2x1wbHKUhQ7r4rjPX4ELvS7vQ2cyQSmxFFeS"
	},
	{
		"slug": "rifle",
		"name": "Vector Rifle",
		"kind": "weapon",
		"label": "Rifle",
		"finish": null,
		"weaponIndex": 0,
		"rarity": "Uncommon",
		"supply": 10,
		"mint": "9BDBMKg8CbDvs2sxBMnaLqTv499swSoh3eB9kkE8K31K"
	},
	{
		"slug": "shotgun",
		"name": "Breach Ward",
		"kind": "weapon",
		"label": "Shotgun",
		"finish": null,
		"weaponIndex": 2,
		"rarity": "Uncommon",
		"supply": 10,
		"mint": "FL4N4bGaY6ZCnX3EWyAabH4YBiejERgYZmQ3sxNpHbDh"
	},
	{
		"slug": "sniper",
		"name": "Long Debt",
		"kind": "weapon",
		"label": "Sniper",
		"finish": null,
		"weaponIndex": 6,
		"rarity": "Legendary",
		"supply": 10,
		"mint": "6q65nqU7SheuUddQm52V7Qc4HvEEnSpo58gPMsGDBC1D"
	},
	{
		"slug": "helm",
		"name": "Degen Helm",
		"kind": "armor",
		"label": "Helm",
		"finish": "Gold",
		"weaponIndex": null,
		"rarity": "Rare",
		"supply": 2,
		"mint": "3utaKyFj5HNCyYWpt3AMTsssQqUsdDsmxFcDS4DBXqJT"
	},
	{
		"slug": "cuirass",
		"name": "Cloth Cuirass",
		"kind": "armor",
		"label": "Cuirass",
		"finish": "Gold",
		"weaponIndex": null,
		"rarity": "Legendary",
		"supply": 2,
		"mint": "CryRyH9XqbtEYER1XvUgbZytpUmN1J3D4FVqhU8Re33c"
	},
	{
		"slug": "pauldron",
		"name": "Cloth Pauldron",
		"kind": "armor",
		"label": "Pauldron",
		"finish": "Gold",
		"weaponIndex": null,
		"rarity": "Uncommon",
		"supply": 2,
		"mint": "BHUYjjKPJ1bRu5wXYFkPBC3qYktz6J7bn9Exa6fBx52o"
	},
	{
		"slug": "caps",
		"name": "Cloth Joint Cap",
		"kind": "armor",
		"label": "Joint Cap",
		"finish": "Gold",
		"weaponIndex": null,
		"rarity": "Common",
		"supply": 2,
		"mint": "8zmYViCu4i23RsEwVS8a2spCZcqtK3aDRqDDrpa56P4V"
	},
	{
		"slug": "sabaton",
		"name": "Cloth Sabaton",
		"kind": "armor",
		"label": "Sabaton",
		"finish": "Gold",
		"weaponIndex": null,
		"rarity": "Uncommon",
		"supply": 2,
		"mint": "5X1m2kpq6HpMyYjT6ze5dV3k9eko5awVJ6NP25imJK6M"
	},
	{
		"slug": "helm-silver",
		"name": "Silver Degen Helm",
		"kind": "armor",
		"label": "Helm",
		"finish": "Silver",
		"weaponIndex": null,
		"rarity": "Rare",
		"supply": 2,
		"mint": "DMobkBUpsCSMDRWP9sESkyMj5WDuRxkuMbDURa4wTvv"
	},
	{
		"slug": "cuirass-silver",
		"name": "Silver Cloth Cuirass",
		"kind": "armor",
		"label": "Cuirass",
		"finish": "Silver",
		"weaponIndex": null,
		"rarity": "Legendary",
		"supply": 2,
		"mint": "ECbXjUru8Tqb6b7PWNXtWP5jgmBNonXiNroT3RhBfH1v"
	},
	{
		"slug": "pauldron-silver",
		"name": "Silver Cloth Pauldron",
		"kind": "armor",
		"label": "Pauldron",
		"finish": "Silver",
		"weaponIndex": null,
		"rarity": "Uncommon",
		"supply": 2,
		"mint": "Cu81Pz9fPnqN4yzkuMfxKLsF8TNZbtXX1VcbcfuXBtpY"
	},
	{
		"slug": "caps-silver",
		"name": "Silver Cloth Joint Cap",
		"kind": "armor",
		"label": "Joint Cap",
		"finish": "Silver",
		"weaponIndex": null,
		"rarity": "Common",
		"supply": 2,
		"mint": "F7CYgWb7zzPDFjvZZQR5pF6T19XqzoTPLc5YsqXkjac2"
	},
	{
		"slug": "sabaton-silver",
		"name": "Silver Cloth Sabaton",
		"kind": "armor",
		"label": "Sabaton",
		"finish": "Silver",
		"weaponIndex": null,
		"rarity": "Uncommon",
		"supply": 2,
		"mint": "BTXzfAVL7ae78oTMiZ4fa8YSbyXeRqickzDjh48PTFfX"
	},
	{
		"slug": "helm-ebony",
		"name": "Ebony Degen Helm",
		"kind": "armor",
		"label": "Helm",
		"finish": "Ebony",
		"weaponIndex": null,
		"rarity": "Rare",
		"supply": 2,
		"mint": "FveHu6dZkMjQ3JA8BdnSHLLLaK1d2av1i9GmkGRodnC7"
	},
	{
		"slug": "cuirass-ebony",
		"name": "Ebony Cloth Cuirass",
		"kind": "armor",
		"label": "Cuirass",
		"finish": "Ebony",
		"weaponIndex": null,
		"rarity": "Legendary",
		"supply": 2,
		"mint": "CWF6QdvDFDJRbVpk6m446snV2KfSh61eF5eb7jk2TYzs"
	},
	{
		"slug": "pauldron-ebony",
		"name": "Ebony Cloth Pauldron",
		"kind": "armor",
		"label": "Pauldron",
		"finish": "Ebony",
		"weaponIndex": null,
		"rarity": "Uncommon",
		"supply": 2,
		"mint": "B22dki1zfi3b2mydYp2n7pEBPUG6dm4aad7hsBbx77yw"
	},
	{
		"slug": "caps-ebony",
		"name": "Ebony Cloth Joint Cap",
		"kind": "armor",
		"label": "Joint Cap",
		"finish": "Ebony",
		"weaponIndex": null,
		"rarity": "Common",
		"supply": 2,
		"mint": "4xpY1c8Y1T7gSSaZRAoLGkqGreKsHN4cw9XiETbzkWdy"
	},
	{
		"slug": "sabaton-ebony",
		"name": "Ebony Cloth Sabaton",
		"kind": "armor",
		"label": "Sabaton",
		"finish": "Ebony",
		"weaponIndex": null,
		"rarity": "Uncommon",
		"supply": 2,
		"mint": "948H5Mf6U7dfxENykbo48PK2Qs4xeaCBkx1YLidMuCc5"
	},
	{
		"slug": "helm-solana",
		"name": "Solana Degen Helm",
		"kind": "armor",
		"label": "Helm",
		"finish": "Solana",
		"weaponIndex": null,
		"rarity": "Rare",
		"supply": 2,
		"mint": "5PDJKG9YJozvqxZX4XZDVMGUkppXdC3wxZCX1uuC2NfZ"
	},
	{
		"slug": "cuirass-solana",
		"name": "Solana Cloth Cuirass",
		"kind": "armor",
		"label": "Cuirass",
		"finish": "Solana",
		"weaponIndex": null,
		"rarity": "Legendary",
		"supply": 2,
		"mint": "UfaBH8Qw82vH7d7ZMvFvyPW7nWGkRxrukK1pQnfGxw9"
	},
	{
		"slug": "pauldron-solana",
		"name": "Solana Cloth Pauldron",
		"kind": "armor",
		"label": "Pauldron",
		"finish": "Solana",
		"weaponIndex": null,
		"rarity": "Uncommon",
		"supply": 2,
		"mint": "7kLEgVxqu1txZTx6YurJ1xo8iPr64uhtxd1EsqwCbTpQ"
	},
	{
		"slug": "caps-solana",
		"name": "Solana Cloth Joint Cap",
		"kind": "armor",
		"label": "Joint Cap",
		"finish": "Solana",
		"weaponIndex": null,
		"rarity": "Common",
		"supply": 2,
		"mint": "FwJ92CZXqoGaFEW3Ze7Y6wzNwo9Lmgq5zbw7zxDrVnY"
	},
	{
		"slug": "sabaton-solana",
		"name": "Solana Cloth Sabaton",
		"kind": "armor",
		"label": "Sabaton",
		"finish": "Solana",
		"weaponIndex": null,
		"rarity": "Uncommon",
		"supply": 2,
		"mint": "HtvSEt1hFEYT47TqbHpSayyjpYF3FxGDwcan3L5TvCvB"
	}
]
