// Generates client/config/armory.js from the MINT RECORD — the file the mainnet mint
// actually wrote — rather than from anything hand-typed.
//
// Why generated: the catalogue has to agree with three things at once (the on-chain names
// in common/entitlements.js, the rarities and supply that were really minted, and the art
// slugs the token metadata points at). Typing 24 entries by hand means 24 chances to
// disagree with the chain, and a disagreement here shows a player an item that does not
// exist or hides one that does.
//
// Run: node scripts/gen-armory.mjs   (writes client/config/armory.js)
import fs from 'fs'
import path from 'path'
import { NFT_ENTITLEMENTS } from '../common/entitlements.js'

const MINTS = '/mnt/echostore/frag-nft/out/mint-results-mainnet.json'
// Permanent-storage transaction ids for every uploaded file, written by the mint. This is
// where the CANONICAL art lives — the same bytes the marketplaces render.
const URIS = '/mnt/echostore/frag-nft/out/arweave-uris.json'
const OUT = path.resolve('client/config/armory.js')

const record = JSON.parse(fs.readFileSync(MINTS, 'utf8'))
const media = JSON.parse(fs.readFileSync(URIS, 'utf8')).media || {}

// Weapon roster order — weakest first, matching the in-game rack rather than the mint
// record's arbitrary key order.
const WEAPON_ORDER = ['smg', 'rifle', 'shotgun', 'sniper']
// Armour reads head-to-toe, and finishes run weakest-looking first (FINISHES order).
const SLOT_ORDER = ['helm', 'cuirass', 'pauldron', 'caps', 'sabaton']
const FINISH_SUFFIX = { Gold: '', Silver: '-silver', Ebony: '-ebony', Solana: '-solana' }

const items = []
for (const [slug, copies] of Object.entries(record.assets)) {
	if (!copies || !copies.length) continue
	const name = copies[0].name
	const ent = NFT_ENTITLEMENTS[name]
	if (!ent) {
		console.warn(`[armory] SKIP "${name}" (${slug}) — no entitlement; it would grant nothing`)
		continue
	}
	items.push({
		slug,
		name,
		kind: ent.kind,
		// weapons carry what they unlock; armour carries where it sits
		label: ent.kind === 'weapon' ? ent.label : ent.slot,
		finish: ent.kind === 'armor' ? ent.finish : null,
		weaponIndex: ent.kind === 'weapon' ? ent.weaponIndex : null,
		rarity: copies[0].rarity,
		supply: copies.length,
		// One real mint per item type, so a card can deep-link to an asset page that
		// exists. NOT a listing — whether this exact copy is for sale is the
		// marketplace's business, and the item page is correct either way.
		mint: copies[0].asset,
		// Permanent-storage id for this item's art. See armoryArt() for why this is the
		// canonical source rather than our own host.
		art: media[slug + '.png'] || null,
		// The turntable render. Same upload, different file — used as the card's moving
		// image, with the still above as its poster.
		video: media[slug + '.mp4'] || null,
	})
}

// Sort into the order the screen shows: weapons first in rack order, then armour by
// finish then by slot head-to-toe.
const FINISH_RANK = { Gold: 0, Silver: 1, Ebony: 2, Solana: 3 }
items.sort((a, b) => {
	if (a.kind !== b.kind) return a.kind === 'weapon' ? -1 : 1
	if (a.kind === 'weapon') {
		return WEAPON_ORDER.indexOf(a.slug) - WEAPON_ORDER.indexOf(b.slug)
	}
	const f = FINISH_RANK[a.finish] - FINISH_RANK[b.finish]
	if (f) return f
	const base = (s) => s.replace(/-(silver|ebony|solana)$/, '')
	return SLOT_ORDER.indexOf(base(a.slug)) - SLOT_ORDER.indexOf(base(b.slug))
})

// sanity: every slug must map back to a real finish suffix, or the art path is wrong
for (const it of items) {
	if (it.kind !== 'armor') continue
	const suffix = FINISH_SUFFIX[it.finish]
	if (suffix === undefined || (suffix && !it.slug.endsWith(suffix))) {
		throw new Error(`[armory] slug/finish mismatch: ${it.slug} claims finish ${it.finish}`)
	}
}

const banner = `// GENERATED by scripts/gen-armory.mjs — do not edit by hand.
//
// The Season 1 catalogue, derived from the mainnet mint record so it cannot disagree with
// what was actually minted, and cross-checked against common/entitlements.js so it cannot
// advertise an item that grants nothing.
//
// \`slug\` is both the mint-record key and the art filename: the token metadata points at
// https://sol-pkmn.fun/nft/degen-s1/<slug>.png, and this screen serves the same files, so
// the armour you see here is the image the marketplace shows.
//
// \`mint\` is ONE real asset of that type — enough to deep-link an item page. It is not a
// claim that this particular copy is listed.
//
// Collection: ${record.collection}
// Minted: ${record.assets ? Object.values(record.assets).reduce((n, a) => n + a.length, 0) : 0} assets across ${items.length} types
`

const body = `${banner}
export const COLLECTION = '${record.collection}'

// Marketplace collection pages. Item-level links are built from a mint below.
export const TENSOR_COLLECTION = 'https://www.tensor.trade/trade/degentournament'
export const MAGIC_EDEN_COLLECTION = 'https://magiceden.io/marketplace/degen_tournament_season_1_armory'
export const tensorItem = (mint) => (mint ? \`https://www.tensor.trade/item/\${mint}\` : TENSOR_COLLECTION)
export const magicEdenItem = (mint) => (mint ? \`https://magiceden.io/item-details/\${mint}\` : MAGIC_EDEN_COLLECTION)

// ART COMES FROM PERMANENT STORAGE, NOT FROM US.
//
// This used to build /nft/degen-s1/<slug>.png against our own origin, and 15 of the 24
// items were broken in production: only the original Gold set and the weapons had ever
// been published there: every Silver, Ebony and Solana piece 404'd. The bytes have always
// existed at their upload transaction — that is what the collection was minted against
// and what the marketplaces render — so pointing at that source removes both the broken
// images and the requirement to keep a second copy of the art in sync with the chain.
//
// gateway.irys.xyz 302-redirects to a CDN; browsers follow it transparently. NOTE: Irys
// is NOT Arweave and arweave.net will NOT resolve these ids.
const GATEWAY = 'https://gateway.irys.xyz/'
export const armoryArt = (item) =>
	item && item.art ? GATEWAY + item.art : \`/nft/degen-s1/\${item && item.slug}.png\`

/** The turntable MP4 for an item, or null if it has none. */
export const armoryVideo = (item) => (item && item.video ? GATEWAY + item.video : null)

export const ARMORY_ITEMS = ${JSON.stringify(items, null, '\t')}
`

fs.writeFileSync(OUT, body)
console.log(`[armory] wrote ${OUT} — ${items.length} types, ${items.reduce((n, i) => n + i.supply, 0)} minted`)
for (const it of items) console.log(`  ${it.kind === 'weapon' ? 'W' : 'A'} ${it.slug.padEnd(18)} ${it.name.padEnd(26)} ${it.rarity.padEnd(10)} x${it.supply}`)
